### ISSUE TITLE
Feature request: non-server-side React library

### ISSUE THREAD

**Issue by dgreene1** [StyraOSS/opa-typescript-deprecated#61]
I see that this library has examples of NodeJS and NestJS. Our UIs use React rendered on the client, so will this library work with that approach?

I ask because when I have used client-side libraries for Permit.io and other vendors, we've had to store a client credential which is unfortunate since that client credential would then be exposed as plaintext in the minified JS. So we need to have a client library that does not require a client secret.

I'll note that I don't see a reference in the readme to a client secret, but that would imply to me that either (a) there is no security code preventing a malicious actor from calling the policy agent or (b) that there is some kind of other mechanism for limiting those who can call the APIs. So which is it? And if it's (b), how do you limit the clients who can call when you don't know the IP of any or all of the users. Perhaps the only limiting you can use is CORS?

Sorry for the ramble.

**Comment by srenatus** [comment]
Heya, thanks for the issue!

As a luck would have it, we're working on the OPA on the frontend iceberg, too, and this includes the React use case.

> I ask because when I have used client-side libraries for Permit.io and other vendors, we've had to store a client credential which is unfortunate since that client credential would then be exposed as plaintext in the minified JS. So we need to have a client library that does not require a client secret.

Yikes! But you're completely right that the frontend use case is special: there, authorization *cannot be trusted* (since it's running on the client side), but it's still required for a good user experience (i.e. don't show a delete button if they're not allowed to delete the thing).

First things first: this library can be used in browsers, it'll use the native `fetch` API. But the library also needs some thing to call, i.e., an OPA instance. That OPA instance needs to be exposed in some way, and there are basically two possibilities:

1. Exposing the OPA API directly, protected through some proxy and a system authorization policy. This would only allow `POST /v1/data/your/frontend/rules`, for example.
2. Exposing the OPA API through whatever API gateway or API service you already have, potentially leveraging your app's authentication measures.

> either (a) there is no security code preventing a malicious actor from calling the policy agent or (b) that there is some kind of other mechanism for limiting those who can call the APIs. So which is it? 

As of now, it's left open. You should be able to use the lib with whatever security mechanism you already have, see (1.) and (2.) for options. But also, this is assuming that you host your OPA instance(s) yourself. Do you?

An altogether different approach we're drafting includes using Wasm. It would mean that a mechanism similar to (1.) or (2.) above would be used not to make an API policy eval request, but to fetch a Wasm module, with which further evals are done client-side. That promises much better performance, at the cost of having to create and distribute the Wasm modules.

What do you think about this?

**Comment by dgreene1** [comment]
So, I get that I can insulate OPA with a proxy, but shouldn’t there be some way to configure OPA itself to only accept requests from certain domains (CORS) or only requests that have correct claims on the token?

Otherwise someone could DoS the OPA PDP right?

As for WASM, it sounds interesting. I’d try it.

**Comment by srenatus** [comment]
> So, I get that I can insulate OPA with a proxy, but shouldn’t there be some way to configure OPA itself to only accept requests from certain domains (CORS) or only requests that have correct claims on the token?

Yes, using [a system authz policy](https://www.openpolicyagent.org/docs/latest/security/#authentication-and-authorization), you can equip OPA with a Rego policy that allows/denies requests based on their HTTP metadata:
```
{
    # Identity value established by authentication scheme.
    # When Bearer tokens are used, the identity is
    # set to the Bearer token value.
    # When TLS client certificates are used, the identity
    # is set to the certificate subject RDNSequence.
    # E.g. "OU=opa-client-01,O=Example"
    # Note: client certificate data is available in the
    # 'client_certificates' key.
    "identity": "",
    
    # Client certificates provided by the client when calling OPA
    # over an mTLS connection. Represented in input as a list of
    # Go x509.Certificate objects marshalled as JSON.
    "client_certificates": [],

    # One of {"GET", "POST", "PUT", "PATCH", "DELETE"}.
    "method": "",

    # URL path represented as an array.
    # For example: /v1/data/exempli-gratia
    # is represented as ["v1", "data", "exampli-gratia"]
    "path": [...],

    # URL parameters represented as an object of string arrays.
    # For example: metrics&explain=true is represented as
    # {"metrics": [""], "explain": ["true"]}
    "params": {"...": ...},

    # Request headers represented as an object of string arrays.
    #
    # Example Request Headers:
    #
    #   host: acmecorp.com
    #   x-custom: secretvalue
    #
    # Example input.headers Value:
    #
    #   {"Host": ["acmecorp.com"], "X-Custom": ["mysecret"]}
    #
    # Example header check:
    #
    #   input.headers["X-Custom"][_] == "mysecret"
    #
    # Header keys follow canonical MIME form. The first character and any
    # characters following a hyphen are uppercase. The rest are lowercase.
    # If the header key contains space or invalid header field bytes,
    # no conversion is performed.
    "headers": {"...": [...]},

    # Request message body if present for applicable APIs.
    #
    # Example Request:
    #
    #   POST v1/data HTTP/1.1
    #   Content-Type: application/json
    #
    #   {"input": {"action": "trade", "stock": "ACME"}}
    #
    # Example input.body Value:
    #
    #   {"input": {"action": "trade", "stock": "ACME"}}
    #
    # Example body check:
    #
    #   input.body.input.stock == "ACME"
    #
    # The 'body' field is provided for the following APIs:
    #
    #   * POST v1/data
    #   * POST v0/data
    #   * POST /
    "body": ...,
}
```

these include the request headers, so you could use it to (for example) validate a JWT token that you've issued to the browser before; or check something CORS-y. ✔️ 

There's nothing built into OPA to prevent excessive requests, though, so rate limits would need to be enforced through another proxy before OPA.

**Comment by srenatus** [comment]
FYI there's a demo in tickethub of using React with _this_ package, either directly, or via OPA's Wasm modules: https://github.com/StyraInc/styra-demo-tickethub/tree/main/client/react#how-to-run-wasm

**Comment by srenatus** [comment]
⏩ It's become its own package now: https://www.npmjs.com/package/@styra/opa-react. You're welcome to give it a try 🥳 I'll close this.
